### ISSUE TITLE
When fetching: `auto_commit` should default to false if `:no_consumer_group` is set

### ISSUE THREAD

**Issue by sdball** [kafkaex/kafka_ex#109]
If I have `consumer_group: :no_consumer_group` then I get errors when fetching from a topic:

```elixir
KafkaEx.fetch("foo", 0, offset: 0)
** (exit) exited in: GenServer.call(KafkaEx.Server, {:fetch, "foo", 0, 0, 10, 1, 1000000, true}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: false
            (kafka_ex) lib/kafka_ex/server.ex:91: KafkaEx.Server.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:564: GenServer.call/3

** (MatchError) no match of right hand side value: false
    (kafka_ex) lib/kafka_ex/server.ex:91: KafkaEx.Server.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:fetch, "foo", 0, 0, 10, 1, 1000000, true}
State: %KafkaEx.Server.State{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "docker", node_id: 0, port: 9092, socket: #Port<0.5371>}], consumer_group: :no_consumer_group, consumer_group_update_interval: 30000, consumer_metadata: %KafkaEx.Protocol.ConsumerMetadata.Response{coordinator_host: "", coordinator_id: 0, coordinator_port: 0, error_code: 0}, correlation_id: 1, event_pid: nil, metadata: %KafkaEx.Protocol.Metadata.Response{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "docker", node_id: 1001, port: 9092, socket: nil}], topic_metadatas: [%KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1001], leader: 1001, partition_id: 0, replicas: [1001]}], topic: "commitlog"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1001], leader: 1001, partition_id: 0, replicas: [1001]}], topic: "foo"}]}, metadata_update_interval: 30000, sync_timeout: 1000, worker_name: KafkaEx.Server}
```

The problem is that `handle_call/3` assumes clients are in a consumer group. Fetching works fine with `auto_commit: false` explicitly set in the call:

```elixir
KafkaEx.fetch("foo", 0, offset: 0, auto_commit: false)
```

It'd be nice for fetch to check if `:no_consumer_group` is set for the consumer group id and then automatically set `auto_commit: false`.

**Comment by dantswain** [comment]
@sdball Good catch.  I'll look into this as soon as I can.  I'm hesitant to do anything _automatically_ because it introduces risk.  At a minimum, we need to update the documentation ASAP to make this more clear.

We have been chatting about this a bit on #kafkaex in the elixir-lang.slack.com if you want to weigh in.  The short answer is we have some medium term plans that might make this moot.

**Comment by sdball** [comment]
Sounds good!

**Comment by dantswain** [comment]
Closing as per discussion here and on #110
