### ISSUE TITLE
Recent SSL addition breaks existing non-SSL configs

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#148]
From an existing application without SSL config:

```
** (Mix) Could not start application kafka_ex: KafkaEx.start(:normal, []) returned an error: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.++(nil, [:ssl])
        (kafka_ex) lib/kafka_ex/network_client.ex:66: KafkaEx.NetworkClient.build_socket_options/1
        (kafka_ex) lib/kafka_ex/network_client.ex:9: KafkaEx.NetworkClient.create_socket/3
        (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:47: anonymous fn/2 in KafkaEx.Server0P9P0.kafka_server_init/1
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:47: KafkaEx.Server0P9P0.kafka_server_init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by bjhaid** [comment]
thanks for catching this:

https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/server_0_p_9_p_0.ex#L40

`@ssloptions` is not defined, which sort of defaults to `nil`

**Comment by bjhaid** [comment]
can you commit a quick fix for this? :) thanks!

**Comment by dantswain** [comment]
Soon as I can - fighting a fire :(
