### ISSUE TITLE
Problem with KafkaEx.stream 

### ISSUE THREAD

**Issue by sweco-semtne** [kafkaex/kafka_ex#183]
Hi,
I'm trying to stream from a single Kafka 0.10.1 Broker with the advertised hostname "b2". 
I had it working but every now and then it gets an exception in 

(kafka_ex) lib/kafka_ex/protocol/fetch.ex:41: KafkaEx.Protocol.Fetch.create_request/1

I can do KakaEx.fetch from the same topic but the streaming doesn´t work.

Any ideas?

```
config :kafka_ex,
  # a list of brokers to connect to in {"HOST", port} format
  brokers: [
    {"b2", 9092}
  ],
  # the default consumer group for worker processes, must be a binary (string)
  #    NOTE if you are on Kafka < 0.8.2 or if you want to disable the use of
  #    consumer groups, set this to :no_consumer_group (this is the
  #    only exception to the requirement that this value be a binary)
  consumer_group: "importer",
  # Set this value to true if you do not want the default
  # `KafkaEx.Server` worker to start during application start-up -
  # i.e., if you want to start your own set of named workers
  disable_default_worker: false,
  # Timeout value, in msec, for synchronous operations (e.g., network calls)
  sync_timeout: 3000,
  # Supervision max_restarts - the maximum amount of restarts allowed in a time frame
  max_restarts: 10,
  # Supervision max_seconds -  the time frame in which :max_restarts applies
  max_seconds: 60
  # This is the flag that enables use of ssl
  #kafka_version: "0.10.0"
```

```
  def importAll do
    importToNeo("orm-route", &writeRouteToNeo/1)
  end
  
  def importToNeo(topic, writer) do
    offset = KafkaEx.latest_offset(topic, 0)
    KafkaEx.stream(topic, 0, offset: offset)
        |> Stream.map(&decodeMessageFromKafka(&1))
        |> Stream.map(writer)
        |> Stream.run
  end

  def decodeMessageFromKafka(%KafkaEx.Protocol.Fetch.Message{value: value}) do
     Poison.decode!(value)
  end

```

```
ex(11)> NeoImport.importAll

11:23:19.909 [debug] Shutting down worker :kafka_ex
:ok
iex(12)>
11:23:19.916 [error] GenServer :kafka_ex terminating
** (ArgumentError) argument error
    (kafka_ex) lib/kafka_ex/protocol/fetch.ex:41: KafkaEx.Protocol.Fetch.create_request/1
    (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:213: KafkaEx.Server0P9P0.fetch/2
    (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:156: KafkaEx.Server0P9P0.kafka_server_start_streaming/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:start_streaming, %KafkaEx.Protocol.Fetch.Request{auto_commit: true, client_id: nil, correlation_id: nil, max_b
ytes: 1000000, min_bytes: 1, offset: [%KafkaEx.Protocol.Offset.Response{partition_offsets: [%{error_code: :no_error, offset: [
316889], partition: 0}], topic: "orm-route"}], partition: 0, topic: "orm-route", wait_time: 10}}
State: %KafkaEx.Server.State{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "b2", node_id: 0, port: 9092, socket: %KafkaEx.
Socket{socket: #Port<0.13714>, ssl: false}}, %KafkaEx.Protocol.Metadata.Broker{host: "b2", node_id: -1, port: 9092, socket: %K
afkaEx.Socket{socket: #Port<0.13713>, ssl: false}}], consumer_group: "importer", consumer_group_update_interval: 30000, consum
er_metadata: %KafkaEx.Protocol.ConsumerMetadata.Response{coordinator_host: "b2", coordinator_id: 0, coordinator_port: 9092, er
ror_code: :no_error}, correlation_id: 28, event_pid: #PID<0.310.0>, metadata: %KafkaEx.Protocol.Metadata.Response{brokers: [%K
afkaEx.Protocol.Metadata.Broker{host: "b2", node_id: 0, port: 9092, socket: nil}], topic_metadatas: [%KafkaEx.Protocol.Metadat
a.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_erro
r, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error,
isrs: [0], leader: 0, partition_id: 6, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isr
s: [0], leader: 0, partition_id: 3, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs:
[0], leader: 0, partition_id: 1, replicas: [0]}
....
```

**Comment by dantswain** [comment]
Thanks for this report, @sweco-semtne!  Can you let us know which version/commit of KafkaEx you're using?

**Comment by dantswain** [comment]
It looks like the problem is that the offset being provided is the raw output of `KafkaEx.latest_offset/3` whereas `KafkaEx.stream/3` wants a number.  You should be able to fix this by doing something like

```
    [offset_data] = KafkaEx.latest_offset(topic, 0)
    [partition_offset_data] = offset_data.partition_offsets
    [offset] = partition_offset.offset
    KafkaEx.stream(topic, 0, offset: offset)
```

@bjhaid Do you recall if this is by design?  It seems a lot of hoops to jump through.  We could modify `stream/3` to extract the offset automatically.

**Comment by sweco-semtne** [comment]
Doh! My bad. 
I agree that it could be made easier ;-)
Thank you for the swift reply!

**Comment by bjhaid** [comment]
@dantswain the API was when I was of the opinion that we will support batching, but that's not happening maybe we should support passing the offset struct to the stream API

**Comment by dantswain** [comment]
Thanks again @sweco-semtne for the report.  I've opened #184 to address the inconsistency.

You may want to ask your question in the #kafkaex channel on the elixir-lang slack.  I'm not sure what you mean by "slow" consumer.  I use the same KafkaEx consumer code to ingest data at rates ranging from a few messages per second to thousands of messages per second.  I don't generally use `stream` myself - I prefer to set up a GenServer that maintains the offsets.  I generally use one GenServer per partition.
