### ISSUE TITLE
Distillery - Compiled Application Trying to Connect To Host That App Was Built On 

### ISSUE THREAD

**Issue by jasongoodwin** [kafkaex/kafka_ex#243]
For some reason, if I compile an application w/ Distillery when my IP address is 192.168.5.106, then get on another network, KafkaEx tries to connect to the IP address I compiled the application on. 

Eg I compiled the app when my IP was 192.168.5.106. Then I try to run it.

This doesn't return anything:
`grep -r 192.168.5.106 ./*`

But in the log I see this:
```
13:58:01.427 application=kafka_ex [debug] Establishing connection to broker 0: "192.168.5.106" on port 9092

13:58:01.429 [error] GenServer #PID<0.1908.0> terminating
** (FunctionClauseError) no function clause matching in KafkaEx.NetworkClient.send_sync_request/3
    (kafka_ex) lib/kafka_ex/network_client.ex:35: KafkaEx.NetworkClient.send_sync_request(nil, <<0, 11, 0, 0, 0, 0, 0, 5, 0, 8, 107, 97, 102, 107, 97, 95, 101, 120, 0, 13, 104, 111, 115, 116, 95, 99, 111, 110, 115, 117, 109, 101, 114, 0, 0, 117, 48, 0, 0, 0, 8, 99, 111, 110, 115, 117, 109, 101, 114, 0, ...>>, 35000)
    (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:79: KafkaEx.Server0P9P0.kafka_server_join_group/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1902.0>): {:join_group, %KafkaEx.Protocol.JoinGroup.Request{group_name: "host_consumer", member_id: "", session_timeout: 30000, topics: ["from_host"]}, 35000}
State: %KafkaEx.Server.State{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "192.168.5.106", node_id: 0, port: 9092, socket: nil}, %KafkaEx.Protocol.Metadata.Broker{host: "127.0.0.1", node_id: -1, port: 9092, socket: %KafkaEx.Socket{socket: #Port<0.4985>, ssl: false}}], consumer_group: "host_consumer", consumer_group_update_interval: 30000, consumer_metadata: %KafkaEx.Protocol.ConsumerMetadata.Response{coordinator_host: "192.168.5.106", coordinator_id: 0, coordinator_port: 9092, error_code: :no_error}, correlation_id: 4, event_pid: nil, metadata: %KafkaEx.Protocol.Metadata.Response{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "192.168.5.106", node_id: 0, port: 9092, socket: nil}], topic_metadatas: [%KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "machine-activities"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "broadcast-ingested"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "machine-cycles"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 6, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 33, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 24, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 42, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 15, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 39, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 30, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 3, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 12, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 48, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 21, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 18, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 9, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 27, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 36, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 45, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 28, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 19, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 1, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 37, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 10, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 34, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 25, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 43, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 7, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 16, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 31, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 22, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 13, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 4, replicas: [0]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 40, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [...], ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{...}, ...], topic: "__consumer_offsets"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "to_host"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: :no_error, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: :no_error, isrs: [0], leader: 0, partition_id: 0, replicas: [0]}], topic: "events"}]}, metadata_update_interval: 30000, ssl_options: [], use_ssl: false, worker_name: #PID<0.1908.0>}
Client #PID<0.1902.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (kafka_ex) lib/kafka_ex/consumer_group/manager.ex:203: KafkaEx.ConsumerGroup.Manager.join/1
    (kafka_ex) lib/kafka_ex/consumer_group/manager.ex:149: KafkaEx.ConsumerGroup.Manager.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

If I change Logger to print application metadata, the connect is (perhaps unsurprisingly) coming from kafka_ex. I can't see how/why this is happening. It looks like there is a broker list - my configuration is explicitly '127.0.0.1' port 9092. Somehow the old IP is added there. I spent a day looking at this - not sure what the cause is or how to resolve it. I can try to create an example project this weekend.

**Comment by dantswain** [comment]
This depends on how your application is set up.  It's important to note that config/config.exs is evaluated at compile time.  So, for example, if you are using `System.get_env`, you may be pulling in the IP of your machine at compile time.  The distillery-built release will be loading a file called `sys.config` that is generated from your mix config.

If you can reproduce with a demo project, that would help a lot.  We use distillery routinely.

**Comment by jasongoodwin** [comment]
K I have an example - I'm pushing it up now. Will leave a link in a moment.

**Comment by jasongoodwin** [comment]
https://github.com/jasongoodwin/kafka_ex_ip_release_issue

**Comment by jasongoodwin** [comment]
I don't see how this is possibly happening.

**Comment by joshuawscott** [comment]
Is this on the same computer as before? Did you restart kafka after changing IPs?

**Comment by joshuawscott** [comment]
I was able to replicate. Kafka advertises an IP address that it determines when it starts up. If the IP address changes, you have to restart kafka or it will continue to hand out that IP.

Simplified flow of connecting to kafka
* App tries to connect to localhost:9092
* Kafka responds "cluster hosts are 192.168.0.2:9092 and 192.168.0.3:9092"
* App connects to 192.168.0.2:9092 and 192.168.0.3:9092
If your host IP changes, then Kafka will now be handing out the wrong IP. You can configure the `advertised.host.name` setting in Kafka to get around this if your IP can change. (e.g. put localhost if you are just testing locally, or put a virtual IP or DNS-backed hostname in production)

**Comment by jasongoodwin** [comment]
Okay im conflating the issues then! Thanks so much.

**Comment by bjhaid** [comment]
@joshuawscott can we close this?
