### ISSUE TITLE
A flag to disable this app while testing other applications

### ISSUE THREAD

**Issue by mzemel** [kafkaex/kafka_ex#43]
I don't mean tests for this project.  I mean projects that have this application as a dependency.

I tried running `mix test --no-start` in my Phoenix project's directory, but I got:

```bash
$ mix test --no-start                                                                                                                                                                                      
** (exit) exited in: GenServer.call(Gide.Repo.Pool, {:query, :begin, &Gide.Repo.log/1, [timeout: 5000]}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (ecto) lib/ecto/adapters/sql.ex:391: Ecto.Adapters.SQL.test_transaction/4
    (elixir) lib/code.ex:307: Code.require_file/2
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
```

If I try to run `mix test` without Kafka running, I get:

```bash
17:10:42.539 [error] Could not connect to broker "192.168.59.103" on port 9092

=INFO REPORT==== 6-Oct-2015::17:10:42 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application kafka_ex: KafkaEx.start(:normal, []) returned an error: an exception was raised:
    ** (FunctionClauseError) no function clause matching in :gen_tcp.send/2
        (kernel) gen_tcp.erl:261: :gen_tcp.send(nil, <<0, 3, 0, 0, 0, 0, 0, 0, 0, 8, 107, 97, 102, 107, 97, 95, 101, 120, 0, 0, 0, 0>>)
        (kafka_ex) lib/kafka_ex/network_client.ex:30: KafkaEx.NetworkClient.send_sync_request/3
        (elixir) lib/enum.ex:1987: Enum.do_find_value/3
        (kafka_ex) lib/kafka_ex/server.ex:246: KafkaEx.Server.metadata/5
        (kafka_ex) lib/kafka_ex/server.ex:26: KafkaEx.Server.init/1
        (stdlib) gen_server.erl:306: :gen_server.init_it/6
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

It would be really cool if there was a flag I could set so I didn't have to build and run a Kafka cluster every time I test my Phoenix application.

**Comment by bjhaid** [comment]
you can exempt it in your `mix.exs` with something like:

```
def application do

  if Mix.env == :test do
    [mod: {Motisoro, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex]]
  else
    [mod: {Motisoro, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex, :kafka_ex]]
  end
end
```

I think you should be dealing with when and how you want `kafka_ex` to start in your application

**Comment by mzemel** [comment]
Ah, thank you.  That works for me!
